// AUTO-GENERATED by auto_test.py
// Timestamp : 2026-05-28T15:38:43.398038
// Git commit : 9fccbfeb03de
// DO NOT EDIT manually – re-run auto_test.py to regenerate

const { test, expect } = require('@playwright/test');

const BASE_URL = 'http://localhost:3000';

test.describe('Auto-generated from code change', () => {
  test('validates changed behavior for public/index.html', async ({ page }) => {
    await page.goto(BASE_URL);

    // Validate that the new text appears and the old text no longer appears.
    await expect(page.getByText('Hackathon Costa Rica 2025')).toBeVisible();
    await expect(page.getByText('Hackathon Costa Rica 2027')).not.toBeVisible();
  });
});
