// AUTO-GENERATED by auto_test.py
// Timestamp : 2026-05-28T18:40:22.874952
// Git commit : d50ec58a9f56
// DO NOT EDIT manually – re-run auto_test.py to regenerate

const { test, expect } = require('@playwright/test');

const BASE_URL = 'http://localhost:3000';

test.describe('Auto-generated from code change', () => {
  test('[public/index.html] "Hackathon Costa Rica 2022" → "Hackathon Costa Rica 2024"', async ({ page }) => {
    await page.goto(BASE_URL);

    // Validate that the new text appears and the old text no longer appears.
    await expect(page.getByText('Hackathon Costa Rica 2024')).toBeVisible();
    await expect(page.getByText('Hackathon Costa Rica 2022')).not.toBeVisible();
  });
});
