// AUTO-GENERATED by auto_test.py
// Timestamp : 2026-05-28T17:51:22.108251
// Git commit : 4db073d81787
// DO NOT EDIT manually – re-run auto_test.py to regenerate

const { test, expect } = require('@playwright/test');

const BASE_URL = 'http://localhost:3000';

test.describe('Auto-generated from code change', () => {
  test('[public/index.html] "Hackathon Costa Rica 2020" → "Hackathon Costa Rica 2022"', async ({ page }) => {
    await page.goto(BASE_URL);

    // Validate that the new text appears and the old text no longer appears.
    await expect(page.getByText('Hackathon Costa Rica 2022')).toBeVisible();
    await expect(page.getByText('Hackathon Costa Rica 2020')).not.toBeVisible();
  });
});
