// AUTO-GENERATED by auto_test.py
// Timestamp : 2026-05-28T15:28:23.878561
// Git commit : 9860c7a4a299
// DO NOT EDIT manually – re-run auto_test.py to regenerate

// @ts-check
const { test, expect } = require('@playwright/test');

const BASE_URL = 'http://localhost:3000';

test.describe('🤖 Auto-generated – Git change detection', () => {

  test('should display updated text "Hackathon Costa Rica 2026"', async ({ page }) => {
    await page.goto(BASE_URL);
    const el = page.locator('#event-text');
    await expect(el).toBeVisible();
    await expect(el).toHaveText('Hackathon Costa Rica 2026');
  });
  test('should NOT display old text "Hackathon Costa Rica 2025"', async ({ page }) => {
    await page.goto(BASE_URL);
    const el = page.locator('#event-text');
    await expect(el).not.toHaveText('Hackathon Costa Rica 2025');
  });
});
